### ISSUE TITLE
[item 01] 정적 팩터리 메서드 단점

### ISSUE THREAD

**Issue by enjoy89** [h-beeen/Malrang#4]
## 🔍 내용
정적 팩터리 메서드는 이름을 가질 수 있어 코드의 가독성을 높이고, 메서드의 기능을 명확히 전달할 수 있다는 큰 장점이 있습니다.
그러나 이와 동시에 **`발견성(Discoverability)`** 이라는 단점이 존재합니다.

발견성 문제란, 메서드가 적절한 이름을 가지고 있어도, 그 존재 자체를 프로그래머가 인지하지 못하면 사용할 수 없다는 것입니다.
특히, 많은 클래스와 라이브러리가 존재하는 대규모 프로젝트에서는 이 문제가 더 두드러집니다.

예를 들어, 프로그래머가 어떤 기능을 구현하려 할 때 해당 기능에 적합한 정적 팩터리 메서드가 존재하는지 모른다면, 결국 직접 구현하거나 비효율적인 방법을 사용하게 될 수 있습니다.

저 역시 이번 아이템을 공부하면서 처음 접한 팩터리 메서드가 많았습니다. 이전에 이를 알았더라면 되게 유용하게 사용했을 것 같아요.. 😅
예를 들어
- `Collections.unmodifiableList(list)` :  주어진 List를 수정할 수 없는 불변의 List로 감싸서 반환하는 기능  
- `Collections.emptyList()`: 빈 List 객체를 반환하는 기능. 불변(empty) List를 생성

이런 발견성 문제를 극복할 수 있는 방법으로 메서드 네이밍 규칙 통일 외에는 어떤 것이 있을까요? 
저는 딱히 떠오르진 않는데.. 이러한 단점보다 얻을 수 있는 장점이 더 많아서 그리 치명적이진 않을 수도 있겠네요..ㅎ

여러분은 실제 플젝하실 때, 저런 여러 메서드를 적극적으로 활용하시는지 궁금하네요
저 처럼 이번 스터디를 하면서 처음 알게된 유용한 메서드가 있으시거나 혹은 실제로 팩터리 메서드를 유용하게 사용한 경험이 있으시면 공유 부탁드려요 😃

## 📚 참고 자료

- [[Java] 불변 객체와 final을 사용해야 하는 이유(feat.정적 팩토리 메소드)](https://seungh1024.tistory.com/72)

**Comment by h-beeen** [comment]
[숫자야구 코드리뷰](https://github.com/woowacourse-precourse/java-baseball-6/pull/1613#discussion_r1372004768)
